services:
  client:
    image: "sasquatch06/fib-client:prod"
    mem_limit: 128m
    hostname: client
  server:
    image: "sasquatch06/fib-server:prod"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "sasquatch06/fib-worker:prod"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "sasquatch06/fib-nginx:prod"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"